name: git-log-txt
on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'
defaults:
  run:
    working-directory: unit-testing-using-dotnet-test
jobs:
  git-log-txt:
    runs-on: windows-latest
    steps:
    - run: git log --oneline > log.txt
