name: build and test
on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'
env:
  DOTNET_VERSION: '5.0.301' # The .NET SDK version to use
defaults:
  run:
    working-directory: unit-testing-using-dotnet-test
jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add Commit
	    run-name: git --no-pager log --oneline > log.txt
